export const ROUTES = {
  LANDING: '/',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  CATEGORIAS: '/categorias',
  COMPRAS: '/compras',
  INSUMOS: '/insumos',
  PRODUCCION: '/produccion',
  PRODUCTOS: '/productos',
  NUEVO_PRODUCTO: '/productos/nuevo',
  AGREGAR_RECETA: '/productos/nuevo/receta',
  PROVEEDORES: '/proveedores',
  ROLES: '/roles',
  USUARIOS: '/usuarios',
  VENTAS: '/ventas',
}
