export { default as CategoriasPage } from './pages/CategoriasPage'
export { useCategorias } from './hooks/useCategorias'
export { categorias, categoriasService, resumenStats, formatDate } from './services/categorias.service'
export { default as EstadoBadge } from './components/EstadoBadge'
export { default as TipoBadge } from './components/TipoBadge'
export { default as CatalogoCategorias } from './components/CatalogoCategorias'
export { default as CategoriasTable } from './components/CategoriasTable'
export { default as PaginacionCategorias } from './components/PaginacionCategorias'
export { default as NuevaCategoriaModal } from './components/NuevaCategoriaModal'
export { default as FiltrosCategoriasDrawer } from './components/FiltrosCategoriasDrawer'
